<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>JaxI18n.Presentation</RootNamespace>
    <AssemblyName>JaxI18n.Presentation</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JaxI18n.Application\JaxI18n.Application.csproj" />
    <ProjectReference Include="..\JaxI18n.Core\JaxI18n.Core.csproj" />
  </ItemGroup>
</Project>
